apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-keyvault
  namespace: dragonball-library
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "{your-keyvault-name}"
  - name: azureClientId
    value: "{your-azure-client-id}" 
  - name: azureTenantId
    value: "{your-azure-tenant-id}" 
scopes:
- apiservice
- backgroundservice