apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-appconfig
  namespace: dragonball-library
spec:
  type: configuration.azure.appconfig
  version: v1
  metadata:
  - name: host 
    value: "https://{your-appconfig-name}.azconfig.io"
  - name: subscribeToKeyChanges
    value: "true"
  - name: azureClientId
    value: "{your-azure-client-id}" 
  - name: azureTenantId
    value: "{your-azure-tenant-id}" 
  auth:
    secretStore: azure-keyvault
scopes:
- apiservice
- backgroundservice