apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-blob-storage
  namespace: dragonball-library
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    value: "{your-storage-account-name}"
  - name: container
    value: "characters"
  - name: azureClientId
    value: "{your-azure-client-id}" 
  - name: azureTenantId
    value: "{your-azure-tenant-id}"  
  auth:
    secretStore: azure-keyvault
scopes:
- apiservice
- backgroundservice