apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dragonball-library
spec:
  type: state.azure.blobstorage
  version: v2
  metadata:
  - name: accountName
    value: "{your-storage-account-name}"
  - name: containerName
    value: "state"
  - name: azureClientId
    value: "{your-azure-client-id}" 
  - name: azureTenantId
    value: "{your-azure-tenant-id}" 
  auth:
    secretStore: azure-keyvault
scopes:
- apiservice